"use client";

/* Signed Supabase image URLs can use deployment-specific hosts. */
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useState } from "react";

import { formatCurrency } from "@/src/lib/currency";
import { getCartLines, setCartLines, subscribeToCart, type CartLine } from "@/lib/cart/browser";
import type { CartProduct } from "@/services/products";

type CartResponse = { products: CartProduct[]; error?: string };
type CartItem = CartProduct & { quantity: number; isAvailable: boolean };

export function CartPage() {
  const [lines, setLines] = useState<CartLine[]>([]); const [items, setItems] = useState<CartItem[]>([]); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading"); const [notice, setNotice] = useState<string | null>(null); const [reload, setReload] = useState(0);
  useEffect(() => { const update = () => setLines(getCartLines()); update(); return subscribeToCart(update); }, []);
  useEffect(() => { if (lines.length === 0) return; let cancelled = false; async function load() { setStatus("loading"); try { const response = await fetch("/api/cart/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productIds: lines.map((line) => line.productId) }) }); const payload = await response.json() as CartResponse; if (!response.ok) throw new Error(payload.error ?? "We couldn’t refresh your bag."); if (cancelled) return; const byId = new Map(payload.products.map((product) => [product.id, product])); const current = lines.flatMap((line) => { const product = byId.get(line.productId); if (!product) return []; const maximum = product.trackInventory ? product.inventoryQuantity : 99; return [{ ...product, quantity: Math.min(line.quantity, Math.max(maximum, 1)), isAvailable: !product.trackInventory || product.inventoryQuantity > 0 }]; }); const normalized = current.map(({ id, quantity }) => ({ productId: id, quantity })); if (JSON.stringify(normalized) !== JSON.stringify(lines)) { setCartLines(normalized); setNotice("Your bag was adjusted to reflect current availability."); } setItems(current); setStatus("ready"); } catch (error) { if (!cancelled) { setStatus("error"); setNotice(error instanceof Error ? error.message : "We couldn’t refresh your bag."); } } } void load(); return () => { cancelled = true; }; }, [lines, reload]);
  const updateQuantity = (productId: string, quantity: number) => setCartLines(lines.map((line) => line.productId === productId ? { ...line, quantity } : line).filter((line) => line.quantity > 0));
  const remove = (productId: string) => setCartLines(lines.filter((line) => line.productId !== productId));
  const subtotal = items.filter((item) => item.isAvailable).reduce((total, item) => total + item.pricePaise * item.quantity, 0); const hasUnavailable = items.some((item) => !item.isAvailable);
  return <main className="mx-auto w-full max-w-[1600px] flex-1 bg-[#f8f7f3] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><p className="font-editorial text-xl">YOUR BAG</p><h1 className="mt-4 text-4xl tracking-[-.05em] sm:text-6xl">A considered selection.</h1>{notice ? <p className="mt-8 border-y border-black/15 py-4 text-sm" role="status">{notice}</p> : null}{lines.length > 0 && status === "loading" ? <p className="mt-16 text-sm text-black/55">Preparing your selection…</p> : null}{status === "error" ? <div className="mt-16 border-y border-black/15 py-8 text-sm"><p>{notice}</p><button className="mt-5 border-b border-black pb-1 text-xs uppercase tracking-[.15em]" onClick={() => setReload((value) => value + 1)} type="button">Try again</button></div> : null}{lines.length === 0 ? <EmptyCart /> : null}{status === "ready" && items.length > 0 ? <div className="mt-16 grid gap-16 lg:grid-cols-[minmax(0,1fr)_22rem] lg:gap-24"><section aria-label="Bag items" className="border-t border-black/15">{items.map((item) => <CartLineItem item={item} key={item.id} onQuantityChange={updateQuantity} onRemove={remove} />)}</section><aside className="lg:sticky lg:top-10 lg:self-start"><p className="font-editorial text-xl">SUMMARY</p><div className="mt-8 flex justify-between border-t border-black/15 pt-5 text-sm"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></div><p className="mt-4 text-xs leading-5 text-black/50">Shipping, taxes and availability are confirmed at checkout.</p><Link aria-disabled={hasUnavailable} className={`mt-10 block bg-black px-5 py-4 text-center text-xs uppercase tracking-[.16em] text-white transition-opacity ${hasUnavailable ? "pointer-events-none opacity-35" : "hover:opacity-75"}`} href="/checkout">Proceed to checkout</Link>{hasUnavailable ? <p className="mt-4 text-xs text-black/50">Remove unavailable pieces before checkout.</p> : null}<Link className="mt-6 inline-block border-b border-black pb-1 text-xs uppercase tracking-[.14em]" href="/shop">Continue browsing</Link></aside></div> : null}</main>;
}

function CartLineItem({ item, onQuantityChange, onRemove }: { item: CartItem; onQuantityChange: (id: string, quantity: number) => void; onRemove: (id: string) => void }) { const max = item.trackInventory ? item.inventoryQuantity : 99; return <article className="grid gap-5 border-b border-black/15 py-8 sm:grid-cols-[10rem_1fr] sm:gap-8"><div className="aspect-square overflow-hidden bg-[#eeece6]">{item.image?.url ? <img alt={item.image.alt} className="size-full object-cover" src={item.image.url} /> : null}</div><div className="flex min-w-0 flex-col"><div className="flex justify-between gap-4"><div><Link className="text-xl tracking-[-.03em]" href={`/products/${item.slug}`}>{item.title}</Link><p className="font-editorial mt-1 text-sm text-black/55">Furniture collection</p></div><p className="shrink-0 text-sm">{formatPrice(item.pricePaise * item.quantity)}</p></div>{!item.isAvailable ? <p className="mt-5 text-xs text-black/50">Currently unavailable</p> : null}<div className="mt-auto flex items-end justify-between gap-4 pt-10"><div className="flex items-center gap-5 border-y border-black/15 py-2 text-sm"><button aria-label={`Decrease ${item.title} quantity`} className="cursor-pointer disabled:opacity-25" disabled={item.quantity <= 1} onClick={() => onQuantityChange(item.id, item.quantity - 1)} type="button">−</button><span aria-live="polite">{item.quantity}</span><button aria-label={`Increase ${item.title} quantity`} className="cursor-pointer disabled:opacity-25" disabled={!item.isAvailable || item.quantity >= max} onClick={() => onQuantityChange(item.id, item.quantity + 1)} type="button">+</button></div><button className="cursor-pointer text-[10px] uppercase tracking-[.15em] text-black/55 transition-opacity hover:opacity-45" onClick={() => onRemove(item.id)} type="button">Remove</button></div></div></article>; }
function EmptyCart() { return <div className="mt-16 border-t border-black/15 py-12"><p className="text-2xl tracking-[-.03em]">Your bag is currently empty.</p><Link className="mt-8 inline-block border-b border-black pb-1 text-xs uppercase tracking-[.15em]" href="/shop">Explore the collection</Link></div>; }
function formatPrice(paise: number) { return formatCurrency(paise); }
