"use server";

import { revalidatePath } from "next/cache";
import { assertAdmin } from "@/lib/auth/admin";
import { productIdSchema, productImageSchema, productInputSchema } from "@/lib/validation/products";
import { archiveAdminProduct, createAdminProduct, removeNewAdminProduct, replaceAdminProductImage, updateAdminProduct } from "@/services/admin-products";

export type ProductActionState = { error?: string; success?: string; fieldErrors?: Record<string, string[]> };

function values(formData: FormData) { return { title: formData.get("title"), description: formData.get("description"), price: formData.get("price"), compareAtPrice: formData.get("compareAtPrice"), sku: formData.get("sku"), inventoryQuantity: formData.get("inventoryQuantity"), categoryId: formData.get("categoryId"), status: formData.get("status") }; }

async function validate(formData: FormData) { await assertAdmin(); const parsed = productInputSchema.safeParse(values(formData)); if (!parsed.success) return { error: undefined, fieldErrors: parsed.error.flatten().fieldErrors, data: null }; const file = formData.get("image"); if (file instanceof File && file.size > 0) { const image = productImageSchema.safeParse(file); if (!image.success) return { error: undefined, fieldErrors: { image: image.error.issues.map((issue) => issue.message) }, data: null }; return { error: undefined, fieldErrors: undefined, data: { input: parsed.data, image: image.data } }; } return { error: undefined, fieldErrors: undefined, data: { input: parsed.data, image: null } }; }

export async function createProduct(_: ProductActionState, formData: FormData): Promise<ProductActionState> { try { const parsed = await validate(formData); if (!parsed.data) return { error: parsed.error, fieldErrors: parsed.fieldErrors }; if (!parsed.data.image) return { fieldErrors: { image: ["A product image is required."] } }; const id = await createAdminProduct(parsed.data.input); try { await replaceAdminProductImage(id, parsed.data.image); } catch (error) { await removeNewAdminProduct(id); return { error: error instanceof Error ? error.message : "Unable to upload image; product was not created." }; } revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: "Product created." }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to create product." }; } }
export async function updateProduct(productId: string, _: ProductActionState, formData: FormData): Promise<ProductActionState> { try { await assertAdmin(); if (!productIdSchema.safeParse(productId).success) return { error: "Invalid product." }; const parsed = productInputSchema.safeParse(values(formData)); if (!parsed.success) return { fieldErrors: parsed.error.flatten().fieldErrors }; const file = formData.get("image"); const image = file instanceof File && file.size > 0 ? productImageSchema.safeParse(file) : null; if (image && !image.success) return { fieldErrors: { image: image.error.issues.map((issue) => issue.message) } }; await updateAdminProduct(productId, parsed.data); if (image?.success) await replaceAdminProductImage(productId, image.data); revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: "Product updated." }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to update product." }; } }
export async function deactivateProduct(productId: string): Promise<ProductActionState> { try { await assertAdmin(); if (!productIdSchema.safeParse(productId).success) return { error: "Invalid product." }; await archiveAdminProduct(productId); revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: "Product deactivated. Historical order records were preserved." }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to deactivate product." }; } }
