import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { ProductGallery } from "@/components/storefront/product-gallery";
import { ProductPurchasePanel } from "@/components/storefront/product-purchase-panel";
import { StorefrontFooter, StorefrontNavbar } from "@/components/storefront/storefront-shell";
import { getProductBySlug, type ProductDetail } from "@/services/products";
import { formatCurrency } from "@/src/lib/currency";
import { storeConfig } from "@/src/config/store";

type ProductPageProps = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: ProductPageProps): Promise<Metadata> { const { slug } = await params; const result = await getProductBySlug(slug); if (!result.data) return { title: `Product not found | ${storeConfig.name}`, robots: { index: false, follow: false } }; const product = result.data; const kind = product.categoryName === "Sofas" ? "Sofa" : product.categoryName === "Armchairs" ? "Armchair" : "Furniture"; const title = `${product.title} ${kind} | Italian Designer Furniture`; const description = product.description?.slice(0, 160) ?? `Discover ${product.title} at ${storeConfig.name}.`; const images = product.images.map((image) => image.url).filter((url): url is string => Boolean(url?.startsWith("https://res.cloudinary.com/"))); return { title, description, alternates: { canonical: `/products/${product.slug}` }, openGraph: { title: `${title} | ${storeConfig.name}`, description, url: `/products/${product.slug}`, type: "website", images: images.map((url) => ({ url })) }, twitter: { card: "summary_large_image", title: `${title} | ${storeConfig.name}`, description, images } }; }

export default async function ProductPage({ params }: ProductPageProps) { const { slug } = await params; const result = await getProductBySlug(slug); if (!result.data && !result.error) notFound(); if (!result.data) throw new Error("Unable to load product."); const product = result.data; const categoryUrl = product.categorySlug ? `/shop/${product.categorySlug}` : "/shop"; const publicImages = product.images.map((image) => image.url).filter((url): url is string => Boolean(url?.startsWith("https://res.cloudinary.com/"))); const productSchema = { "@context": "https://schema.org", "@type": "Product", name: product.title, description: product.description ?? undefined, image: publicImages.length ? publicImages : undefined, brand: { "@type": "Brand", name: storeConfig.name }, category: product.categoryName ?? undefined, offers: { "@type": "Offer", url: `${storeConfig.siteUrl}/products/${product.slug}`, priceCurrency: "INR", price: String(product.pricePaise / 100), availability: product.isInStock ? "https://schema.org/InStock" : "https://schema.org/OutOfStock" } }; const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: storeConfig.siteUrl }, { "@type": "ListItem", position: 2, name: "Shop", item: `${storeConfig.siteUrl}/shop` }, { "@type": "ListItem", position: 3, name: product.categoryName ?? "Collection", item: `${storeConfig.siteUrl}${categoryUrl}` }, { "@type": "ListItem", position: 4, name: product.title, item: `${storeConfig.siteUrl}/products/${product.slug}` }] }; return <div className="min-h-screen bg-[#f8f7f3] text-black"><StorefrontNavbar /><main className="mx-auto max-w-[1600px] px-5 py-8 sm:px-8 lg:px-12 lg:py-12"><script dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} type="application/ld+json" /><script dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} type="application/ld+json" /><Link className="text-xs uppercase tracking-[.15em] text-black/55 transition-opacity hover:opacity-100" href={categoryUrl}>← {product.categoryName ?? "Collection"}</Link><section className="mt-8 grid gap-12 lg:grid-cols-[minmax(0,1.45fr)_minmax(300px,.55fr)] lg:gap-20"><ProductGallery images={product.images} title={product.title} /><ProductInfo product={product} /></section></main><StorefrontFooter /></div>; }

function ProductInfo({ product }: { product: ProductDetail }) { return <div className="lg:pt-8"><p className="font-editorial text-lg text-black/60">{product.categoryName ?? "Novae Collection"}</p><h1 className="mt-3 text-4xl leading-none tracking-[-.055em] sm:text-6xl">{product.title}</h1><p className="mt-6 text-lg">{formatCurrency(product.pricePaise)}</p>{product.description ? <div className="mt-12 border-t border-black/15 pt-6"><p className="text-xs uppercase tracking-[.15em] text-black/50">Details</p><p className="mt-4 whitespace-pre-line text-sm leading-7 text-black/70">{product.description}</p></div> : null}<ProductPurchasePanel product={product} /></div>; }
