import "server-only";

import { createServerSupabaseClient } from "@/lib/supabase/server";
import type { FulfillmentStatus } from "@/lib/validation/orders";

export type AdminOrder = { id: string; orderNumber: string; customerName: string; customerEmail: string; totalPaise: number; paymentStatus: string; orderStatus: string; fulfillmentStatus: FulfillmentStatus; createdAt: string };
export type AdminOrderPage = { items: AdminOrder[]; total: number; page: number; totalPages: number };
export type AdminOrderDetail = AdminOrder & { customerPhone: string | null; shipping: { recipientName?: string; phone?: string; addressLine1?: string; addressLine2?: string; city?: string; state?: string; postalCode?: string; country?: string }; subtotalPaise: number; shippingPaise: number; discountPaise: number; taxPaise: number; razorpayOrderId: string | null; items: Array<{ id: string; title: string; sku: string | null; quantity: number; unitPricePaise: number; totalPaise: number }>; payment: { status: string; razorpayOrderId: string | null; razorpayPaymentId: string | null; capturedAt: string | null } | null };

const PER_PAGE = 20;
const paymentStatuses = ["pending", "created", "authorized", "captured", "failed", "refunded", "cancelled"];
const orderStatuses = ["created", "payment_pending", "paid", "processing", "shipped", "delivered", "cancelled", "refunded", "expired"];
type OrderRow = { id: string; order_number: string; customer_name: string; customer_email: string; customer_phone: string | null; total_paise: number; subtotal_paise: number; shipping_paise: number; discount_paise: number; tax_paise: number; payment_status: string; status: string; fulfillment_status: FulfillmentStatus; created_at: string; shipping_address: AdminOrderDetail["shipping"]; razorpay_order_id: string | null; order_items: Array<{ id: string; product_title: string; sku: string | null; quantity: number; unit_price_paise: number; total_paise: number }> | null; payments: Array<{ status: string; razorpay_order_id: string | null; razorpay_payment_id: string | null; created_at: string; updated_at: string }> | null };
function summary(row: OrderRow): AdminOrder { return { id: row.id, orderNumber: row.order_number, customerName: row.customer_name, customerEmail: row.customer_email, totalPaise: Number(row.total_paise), paymentStatus: row.payment_status, orderStatus: row.status, fulfillmentStatus: row.fulfillment_status, createdAt: row.created_at }; }

export async function getAdminOrders({ q = "", payment = "", status = "", sort = "newest", page = 1 }: { q?: string; payment?: string; status?: string; sort?: string; page?: number }): Promise<{ data: AdminOrderPage; error: string | null }> {
  const safePage = Math.max(1, Math.min(page, 10_000));
  try { const supabase = await createServerSupabaseClient(); let query = supabase.from("orders").select("id,order_number,customer_name,customer_email,customer_phone,total_paise,subtotal_paise,shipping_paise,discount_paise,tax_paise,payment_status,status,fulfillment_status,created_at,shipping_address,razorpay_order_id,order_items(id,product_title,sku,quantity,unit_price_paise,total_paise),payments(status,razorpay_order_id,razorpay_payment_id,created_at,updated_at)", { count: "exact" }); const escaped = q.replace(/[%_,()]/g, ""); if (escaped) query = query.or(`order_number.ilike.%${escaped}%,customer_name.ilike.%${escaped}%,customer_email.ilike.%${escaped}%`); if (paymentStatuses.includes(payment)) query = query.eq("payment_status", payment); if (orderStatuses.includes(status)) query = query.eq("status", status); const { data, error, count } = await query.order("created_at", { ascending: sort === "oldest" }).range((safePage - 1) * PER_PAGE, safePage * PER_PAGE - 1); if (error) throw error; const total = count ?? 0; return { data: { items: ((data ?? []) as unknown as OrderRow[]).map(summary), total, page: safePage, totalPages: Math.ceil(total / PER_PAGE) }, error: null }; } catch { return { data: { items: [], total: 0, page: safePage, totalPages: 0 }, error: "Unable to load orders. Please try again." }; }
}

export async function getAdminOrder(id: string): Promise<{ data: AdminOrderDetail | null; error: string | null }> { try { const supabase = await createServerSupabaseClient(); const { data, error } = await supabase.from("orders").select("id,order_number,customer_name,customer_email,customer_phone,total_paise,subtotal_paise,shipping_paise,discount_paise,tax_paise,payment_status,status,fulfillment_status,created_at,shipping_address,razorpay_order_id,order_items(id,product_title,sku,quantity,unit_price_paise,total_paise),payments(status,razorpay_order_id,razorpay_payment_id,created_at,updated_at)").eq("id", id).maybeSingle(); if (error) throw error; if (!data) return { data: null, error: null }; const row = data as unknown as OrderRow; const payment = row.payments?.[0] ?? null; return { data: { ...summary(row), customerPhone: row.customer_phone, shipping: row.shipping_address ?? {}, subtotalPaise: Number(row.subtotal_paise), shippingPaise: Number(row.shipping_paise), discountPaise: Number(row.discount_paise), taxPaise: Number(row.tax_paise), razorpayOrderId: row.razorpay_order_id, items: (row.order_items ?? []).map((item) => ({ id: item.id, title: item.product_title, sku: item.sku, quantity: item.quantity, unitPricePaise: Number(item.unit_price_paise), totalPaise: Number(item.total_paise) })), payment: payment ? { status: payment.status, razorpayOrderId: payment.razorpay_order_id, razorpayPaymentId: payment.razorpay_payment_id, capturedAt: payment.status === "captured" ? payment.updated_at : null } : null }, error: null }; } catch { return { data: null, error: "Unable to load this order. Please try again." }; } }

const transitions: Record<FulfillmentStatus, FulfillmentStatus[]> = { unfulfilled: ["confirmed", "cancelled"], confirmed: ["processing", "cancelled"], processing: ["shipped", "cancelled"], shipped: ["delivered"], delivered: [], cancelled: [] };
export async function updateAdminFulfillment(id: string, next: FulfillmentStatus) { const supabase = await createServerSupabaseClient(); const { data: existing, error: findError } = await supabase.from("orders").select("fulfillment_status,payment_status").eq("id", id).maybeSingle(); if (findError || !existing) throw new Error("Order not found."); const current = existing.fulfillment_status as FulfillmentStatus; if (!transitions[current]?.includes(next)) throw new Error("That fulfillment transition is not allowed."); if (existing.payment_status !== "captured") throw new Error("Fulfillment can only be updated after verified payment."); const { error } = await supabase.from("orders").update({ fulfillment_status: next }).eq("id", id).eq("fulfillment_status", current).eq("payment_status", "captured"); if (error) throw new Error("Unable to update fulfillment. Please refresh and try again."); }
