import "server-only";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export type AdminCustomer = { id: string; name: string; email: string; phone: string | null; orderCount: number; totalSpentPaise: number; lastOrderAt: string | null };
export type AdminCustomerDetail = AdminCustomer & { orders: Array<{ id: string; orderNumber: string; totalPaise: number; paymentStatus: string; fulfillmentStatus: string; createdAt: string }> };
const PER_PAGE = 20;
type CustomerSummaryRow = { id: string; name: string; email: string; phone: string | null; order_count: number; total_spent_paise: number; last_order_at: string | null; total_count: number };
function map(row: CustomerSummaryRow): AdminCustomer { return { id: row.id, name: row.name, email: row.email, phone: row.phone, orderCount: Number(row.order_count), totalSpentPaise: Number(row.total_spent_paise), lastOrderAt: row.last_order_at }; }
export async function getAdminCustomers({ q = "", page = 1 }: { q?: string; page?: number }) { const safePage = Math.max(1, Math.min(page, 10_000)); try { const supabase = await createServerSupabaseClient(); const { data, error } = await supabase.rpc("admin_customer_summaries", { search_term: q, page_offset: (safePage - 1) * PER_PAGE, page_limit: PER_PAGE }); if (error) throw error; const rows = (data ?? []) as CustomerSummaryRow[]; const total = rows[0]?.total_count ?? 0; return { data: { items: rows.map(map), page: safePage, total, totalPages: Math.ceil(total / PER_PAGE) }, error: null as string | null }; } catch { return { data: { items: [], page: safePage, total: 0, totalPages: 0 }, error: "Unable to load customers. Please try again." }; } }
export async function getAdminCustomer(id: string): Promise<{ data: AdminCustomerDetail | null; error: string | null }> { try { const supabase = await createServerSupabaseClient(); const [{ data: customer, error: customerError }, { data: orders, error: ordersError }] = await Promise.all([supabase.from("customers").select("id,name,email,phone").eq("id", id).maybeSingle(), supabase.from("orders").select("id,order_number,total_paise,payment_status,fulfillment_status,created_at").eq("customer_id", id).order("created_at", { ascending: false })]); if (customerError || ordersError) throw new Error(); if (!customer) return { data: null, error: null }; const allOrders = orders ?? []; const captured = allOrders.filter((order) => order.payment_status === "captured"); const latest = allOrders[0]?.created_at ?? null; return { data: { id: customer.id, name: customer.name, email: customer.email, phone: customer.phone, orderCount: allOrders.length, totalSpentPaise: captured.reduce((sum, order) => sum + Number(order.total_paise), 0), lastOrderAt: latest, orders: allOrders.map((order) => ({ id: order.id, orderNumber: order.order_number, totalPaise: Number(order.total_paise), paymentStatus: order.payment_status, fulfillmentStatus: order.fulfillment_status, createdAt: order.created_at })) }, error: null }; } catch { return { data: null, error: "Unable to load this customer. Please try again." }; } }
