import { AlertCircle, ArrowUpRight, BadgeIndianRupee, Package, ShoppingCart, Users } from "lucide-react";

import { getAdminDashboard } from "@/services/admin-dashboard";

export default async function AdminPage() {
  const result = await getAdminDashboard();
  const dashboard = result.data;

  return <main className="mx-auto max-w-7xl p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Overview</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-2 text-sm text-muted-foreground">A live view of your store’s performance.</p></div><p className="text-xs text-muted-foreground">All-time totals</p></div>{result.error ? <div className="mt-6 flex gap-3 rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive"><AlertCircle className="size-5 shrink-0" />{result.error}</div> : null}<section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BadgeIndianRupee} label="Revenue" value={formatPrice(dashboard.revenuePaise)} /><Metric icon={ShoppingCart} label="Orders" value={dashboard.orderCount.toLocaleString("en-IN")} /><Metric icon={Users} label="Customers" value={dashboard.customerCount.toLocaleString("en-IN")} /><Metric icon={Package} label="Active products" value={dashboard.activeProductCount.toLocaleString("en-IN")} /></section><section className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(18rem,.8fr)]"><RecentOrders orders={dashboard.recentOrders} /><Inventory inventory={dashboard.inventory} outOfStockCount={dashboard.outOfStockCount} /></section></main>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Package; label: string; value: string }) { return <article className="rounded-xl border bg-background p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-muted-foreground">{label}</p><span className="grid size-9 place-items-center rounded-md bg-muted"><Icon className="size-4" /></span></div><p className="mt-5 text-2xl font-semibold tracking-tight">{value}</p></article>; }
function RecentOrders({ orders }: { orders: Awaited<ReturnType<typeof getAdminDashboard>>["data"]["recentOrders"] }) { return <section className="rounded-xl border bg-background"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">Recent orders</h2><p className="mt-1 text-sm text-muted-foreground">Latest activity across your store.</p></div><ArrowUpRight className="size-4 text-muted-foreground" /></div>{orders.length === 0 ? <Empty label="Orders will appear here once customers start checking out." /> : <div className="overflow-x-auto border-t"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Order</th><th className="px-5 py-3 font-medium">Customer</th><th className="px-5 py-3 font-medium">Amount</th><th className="px-5 py-3 font-medium">Payment</th><th className="px-5 py-3 font-medium">Order status</th><th className="px-5 py-3 font-medium">Date</th></tr></thead><tbody className="divide-y">{orders.map((order) => <tr key={order.id}><td className="px-5 py-4 font-medium">{order.orderNumber}</td><td className="px-5 py-4">{order.customerName}</td><td className="px-5 py-4">{formatPrice(order.totalPaise)}</td><td className="px-5 py-4"><Status value={order.paymentStatus} /></td><td className="px-5 py-4"><Status value={order.orderStatus} /></td><td className="px-5 py-4 text-muted-foreground">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(order.createdAt))}</td></tr>)}</tbody></table></div>}</section>; }
function Inventory({ inventory, outOfStockCount }: { inventory: Awaited<ReturnType<typeof getAdminDashboard>>["data"]["inventory"]; outOfStockCount: number }) { return <section className="rounded-xl border bg-background"><div className="p-5"><h2 className="font-semibold">Inventory watch</h2><p className="mt-1 text-sm text-muted-foreground">{outOfStockCount > 0 ? `${outOfStockCount} product${outOfStockCount === 1 ? " is" : "s are"} out of stock.` : "No products are out of stock."}</p></div><div className="border-t">{inventory.length === 0 ? <Empty label="Inventory levels look healthy." /> : inventory.map((product) => <div className="flex items-center justify-between gap-4 border-b px-5 py-4 last:border-b-0" key={product.id}><p className="min-w-0 truncate text-sm font-medium">{product.title}</p><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-medium ${product.isOutOfStock ? "bg-destructive/10 text-destructive" : "bg-amber-500/10 text-amber-700"}`}>{product.isOutOfStock ? "Out of stock" : `${product.inventoryQuantity} left`}</span></div>)}</div></section>; }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-muted px-2 py-1 text-xs capitalize text-muted-foreground">{value.replaceAll("_", " ")}</span>; }
function Empty({ label }: { label: string }) { return <p className="p-8 text-center text-sm text-muted-foreground">{label}</p>; }
function formatPrice(paise: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100); }
