import Link from "next/link";
import { Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AdminCustomer } from "@/services/admin-customers";
import { formatCurrency } from "@/src/lib/currency";
type Page = { items: AdminCustomer[]; page: number; total: number; totalPages: number };
export function CustomerTable({ customers, q }: { customers: Page; q: string }) { const url = (page: number) => `/admin/customers?${new URLSearchParams({ ...(q ? { q } : {}), page: String(page) })}`; return <section className="mt-8"><form className="flex gap-3"><label className="relative flex-1"><span className="sr-only">Search customers</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input className="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm" defaultValue={q} name="q" placeholder="Search name, email, or phone" type="search" /></label><Button type="submit" variant="outline">Search</Button></form><div className="mt-5 overflow-x-auto rounded-xl border bg-background"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Orders</th><th className="px-5 py-3">Total spent</th><th className="px-5 py-3">Last order</th></tr></thead><tbody className="divide-y">{customers.items.map((customer) => <tr key={customer.id}><td className="px-5 py-4"><Link className="font-medium hover:underline" href={`/admin/customers/${customer.id}`}>{customer.name}</Link><p className="mt-1 text-xs text-muted-foreground">{customer.email}</p></td><td className="px-5 py-4 text-muted-foreground">{customer.phone ?? "—"}</td><td className="px-5 py-4">{customer.orderCount}</td><td className="px-5 py-4">{money(customer.totalSpentPaise)}</td><td className="px-5 py-4 text-muted-foreground">{customer.lastOrderAt ? date(customer.lastOrderAt) : "—"}</td></tr>)}</tbody></table>{customers.items.length === 0 ? <div className="p-12 text-center"><p className="font-medium">No customers found</p><p className="mt-1 text-sm text-muted-foreground">Customer records are created from checkout activity.</p></div> : null}</div>{customers.totalPages > 1 ? <div className="mt-5 flex justify-between text-sm"><span className="text-muted-foreground">Page {customers.page} of {customers.totalPages}</span><div className="flex gap-2"><Button disabled={customers.page <= 1} render={<Link href={url(customers.page - 1)} />} variant="outline">Previous</Button><Button disabled={customers.page >= customers.totalPages} render={<Link href={url(customers.page + 1)} />} variant="outline">Next</Button></div></div> : null}</section>; }
export function money(value: number) { return formatCurrency(value, 2); }
export function date(value: string) { return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)); }
