-- Replace the storefront demo catalogue without deleting product/order history.
begin;

insert into public.categories (name, slug, description, is_active, sort_order) values
  ('Armchairs', 'armchairs', 'Italian armchairs defined by craft and material.', true, 1),
  ('Sofas', 'sofas', 'Italian sofas designed for enduring comfort.', true, 2)
on conflict (slug) do update set name = excluded.name, description = excluded.description, is_active = true, sort_order = excluded.sort_order;

-- Preserve historical product references and snapshots: demo products are archived, not deleted.
update public.products set status = 'archived', updated_at = now()
where slug in ('essential-oversized-tee','premium-cotton-shirt','everyday-relaxed-hoodie','minimal-linen-overshirt','classic-leather-wallet','everyday-canvas-backpack','minimal-steel-watch','urban-runner-sneakers','classic-court-sneakers','everyday-slip-on');
update public.categories set is_active = false, updated_at = now() where slug in ('apparel', 'accessories', 'footwear');
delete from public.product_images using public.products where product_images.product_id = products.id and products.slug in ('essential-oversized-tee','premium-cotton-shirt','everyday-relaxed-hoodie','minimal-linen-overshirt','classic-leather-wallet','everyday-canvas-backpack','minimal-steel-watch','urban-runner-sneakers','classic-court-sneakers','everyday-slip-on');

insert into public.products (title, slug, description, status, price_paise, sku, inventory_quantity, track_inventory, category_id, meta_title, meta_description)
select v.title, v.slug, v.description, 'active', v.price_paise, v.sku, 10, false, c.id, v.title || ' | Novae Studio', v.description
from (values
  ('Bachi','bachi',15000000::bigint,'NOVAE-BACHI-001','armchairs','Armchair upholstered in leather or fabric with a structure in multilayer wood and solid fir. The seat and backrest consist of two independent elements padded in polyurethane and Memory Foam®, folded and shaped to create an enveloping form inspired by silkworm cocoons. The two parts are joined by a metal base with feet that enhances stability and seating comfort.'),
  ('Hampshire','hampshire',17000000::bigint,'NOVAE-HAMPSHIRE-001','armchairs','Armchair upholstered in leather or fabric with a curved structure in multilayer poplar. The seat, supported by elastic webbing, combines polyurethane and Memory Foam® padding for enhanced comfort. Backrest and armrests form a continuous, enveloping volume, while the sculpted multilayer birch base in high-gloss polyester finish adds a refined and dynamic presence.'),
  ('Pavone Armchair','pavone-armchair',19000000::bigint,'NOVAE-PAVONE-001','armchairs','Armchair in leather or fabric inspired by the silhouette of a peacock, with a dramatic shell in brass and steel evoking the spread of plumage. Armrests and backrest form a crown of hand-polished cast brass elements, completed by upholstered cushions. The seat and lumbar support are made of multi-density polyurethane with an acrylic fiber layer. Chrome-plated metal base and a pedestal wrapped in leather. Metal parts are available in the full range of selected finishes.'),
  ('Joker','joker',50000000::bigint,'NOVAE-JOKER-001','sofas','Modular sofa upholstered in leather or fabric with a structure in multilayer wood and fir blockboard, supported by elastic webbing. Seat cushions in multi-density polyurethane with Memory Foam® and acrylic fiber ensure comfort, while supersoft backrests enhance softness. Pleated upholstery with contrasting leather piping and aluminum details defines the profile, complemented by metal armrests or padded versions on request.'),
  ('Frame','frame',62000000::bigint,'NOVAE-FRAME-001','sofas','Modular sofa upholstered in leather or fabric with a structure in multilayer wood and solid poplar and fir, supported by elastic webbing. Seat cushions in multi-density polyurethane with Memory Foam® and feather ensure comfort, while hollow armrests integrate satin stainless steel inserts functioning as open storage elements. The rear of the backrests is finished with decorative aluminum plates with a textured effect. Metal parts are available in the selection of metal finishes.'),
  ('Walker','walker',70000000::bigint,'NOVAE-WALKER-001','sofas','Modular sofa, padded and upholstered in leather or fabric, with a thick goose down quilt secured to the solid and multilayer wood frame by tension straps. The seat, supported by elastic webbing, features cushions in polyurethane and Memory Foam® wrapped in a chambered down quilt. Extended armrests and backrests, also quilted with straps, create a voluminous duvet effect for ultimate softness.')
) as v(title, slug, price_paise, sku, category_slug, description) join public.categories c on c.slug = v.category_slug
on conflict (slug) do update set title = excluded.title, description = excluded.description, status = 'active', price_paise = excluded.price_paise, sku = excluded.sku, inventory_quantity = excluded.inventory_quantity, track_inventory = excluded.track_inventory, category_id = excluded.category_id, meta_title = excluded.meta_title, meta_description = excluded.meta_description, updated_at = now();

delete from public.product_images using public.products where product_images.product_id = products.id and products.slug in ('bachi','hampshire','pavone-armchair','joker','frame','walker');
insert into public.product_images (product_id, storage_path, alt_text, sort_order)
select p.id, v.url, p.title, v.sort_order from public.products p join (values
 ('bachi',0,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1776440054/visionnaire_website_prd/Visionnaire_Bachi_Armchair_1807_cafb1fdb9b?_a=BAVMn6E70'),('bachi',1,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1776611052/visionnaire_website_prd/3_859ede7b22?_a=BAVMn6E70'),
 ('hampshire',0,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1779198056/visionnaire_website_prd/Visionnaire_Hampshire_Armchair_2039_dc51f71db8?_a=BAVMn6E70'),('hampshire',1,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1776527597/visionnaire_website_prd/1_0f391c926b?_a=BAVMn6E70'),
 ('pavone-armchair',0,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1751533830/visionnaire_website_prd/Visionnaire_Pavone_poltrona_3_2d3a75ddb2?_a=BAVMn6E70'),('pavone-armchair',1,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1753190352/visionnaire_website_prd/Visionnaire_Vertical_Gallery_Pavone1_a4cdd18143?_a=BAVMn6E70'),
 ('joker',0,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1776414421/visionnaire_website_prd/Visionnaire_Joker_Sofa_20260040_3c5daf79c7?_a=BAVMn6E70'),('joker',1,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1782136731/visionnaire_website_prd/Visionnaire_Joker_Sofa_Website4_310fed4c92?_a=BAVMn6E70'),
 ('frame',0,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1776502560/visionnaire_website_prd/Visionnaire_Frame_Sofa_20260588_dc7c77e238?_a=BAVMn6E70'),('frame',1,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1781879148/visionnaire_website_prd/Visionnaire_Frame_Sofa_Website8_b28a886d12?_a=BAVMn6E70'),
 ('walker',0,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1751876935/visionnaire_website_prd/Visionnaire_Walker_Tessuto_divano_7102ddff38?_a=BAVMn6E70'),('walker',1,'https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_3840/f_auto/q_auto:best/v1753188239/visionnaire_website_prd/GALLERY_CON_SLIDER_PDP_Walker_915016c4c5?_a=BAVMn6E70')
) as v(slug, sort_order, url) on p.slug = v.slug;
commit;
