import Image from "next/image";
import Link from "next/link";

import { StorefrontFooter, StorefrontNavbar } from "@/components/storefront/storefront-shell";

const armchairsImage = "https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_1080/f_auto/q_auto:best/v1776527597/visionnaire_website_prd/1_0f391c926b?_a=BAVMn6E70";
const sofasImage = "https://res.cloudinary.com/dpups1csk/image/upload/c_limit,w_1080/f_auto/q_auto:best/v1781789309/visionnaire_website_prd/Visionnaire_Bold_Sofa_Website2_11452db0dc?_a=BAVMn6E70";

export default function StorefrontHomePage() {
  return <div className="min-h-screen bg-[#f8f7f3] text-black"><section className="relative min-h-svh overflow-hidden bg-black text-white"><div className="absolute inset-0 overflow-hidden"><iframe allow="autoplay; fullscreen; picture-in-picture" className="pointer-events-none absolute left-1/2 top-1/2 h-[177.78vw] min-h-[100svh] w-[100vw] min-w-[177.78svh] -translate-x-1/2 -translate-y-1/2" src="https://player.vimeo.com/video/1192308851?autoplay=1&muted=1&loop=1&background=1&autopause=0&playsinline=1" title="Novae Studio collection film" /><div className="absolute inset-0 bg-black/25" /></div><StorefrontNavbar variant="overlay" /><div className="relative z-10 flex min-h-svh items-end px-5 pb-10 sm:px-8 sm:pb-14 lg:px-12"><p className="max-w-xs text-[10px] uppercase leading-5 tracking-[.18em] text-white/75">Italian furniture for rooms that outlast the moment.</p></div></section><main><section className="mx-auto max-w-[1120px] px-5 py-28 sm:px-8 sm:py-40"><p className="font-editorial text-xl">NOVAE STUDIO</p><h1 className="mt-8 max-w-4xl text-3xl leading-[1.13] tracking-[-.045em] sm:text-5xl lg:text-6xl">Italian furniture shaped by rigorous craft, generous material and a belief in design that remains.</h1></section><section className="mx-auto max-w-[1600px] px-5 pb-20 sm:px-8 lg:px-12 lg:pb-32"><div className="grid items-end gap-10 lg:grid-cols-2 lg:gap-20"><CollectionSpread href="/shop?category=armchairs" image={armchairsImage} title="ARMCHAIRS" /><CollectionSpread delayed href="/shop?category=sofas" image={sofasImage} title="SOFAS" /></div></section><section className="border-t border-black/10 px-5 py-28 sm:px-8 sm:py-40 lg:px-12"><div className="mx-auto grid max-w-[1600px] items-end gap-10 lg:grid-cols-[1fr_1fr]"><p className="font-editorial text-xl">MEET OUR DESIGNERS</p><div><p className="max-w-xl text-3xl leading-[1.15] tracking-[-.04em] sm:text-5xl">A point of view formed through proportion, touch and the quiet intelligence of a well-made object.</p><Link className="mt-10 inline-block border-b border-black pb-1 text-xs uppercase tracking-[.16em] transition-opacity hover:opacity-50" href="/shop">Discover the collection</Link></div></div></section></main><StorefrontFooter /></div>;
}

function CollectionSpread({ href, image, title, delayed = false }: { href: string; image: string; title: string; delayed?: boolean }) {
  return <article className={delayed ? "lg:translate-y-28" : ""}><Link className="group block" href={href}><div className="relative aspect-square overflow-hidden bg-stone-200"><Image alt={`${title} collection`} className="object-cover transition-transform duration-700 ease-out group-hover:scale-[1.02]" fill priority sizes="(min-width: 1024px) 46vw, 100vw" src={image} /></div><div className="mt-5 flex items-baseline justify-between"><h2 className="font-editorial text-2xl">{title}</h2><span className="text-xs uppercase tracking-[.15em]">Explore Collection</span></div></Link></article>;
}
